### ISSUE TITLE
html_to_image cache and return wrong screenshot

### ISSUE THREAD

**Issue by ariaieboy** [rest7/api#12]
hello 
i just test your api and i used html_to_image api i send google.com url its send me the google website screenshot and that was great after that i request for yahoo.com and its return the prev screenshot that was for google
i think that its cache my prev request and send me the exact prev picture just with diff name 
i must wait some time or change my ip so i can request another url 
any fix for this issue ?

**Comment by ArtemisFowlJnr** [comment]
Having same issue, I requested https://example.com and now I can get nothing but that. Fix would be appreciated if possible!
The strange thing is that this is only when querying through my app (python). When I use Firefox, everything works as normal.
```python
>>> import requests as req
>>> r = req.get('http://api.rest7.com/v1/html_to_image.php?url=http://example.com&format=png')
>>> r.json()['file']
'http://api.rest7.com/temp/1567634400/d41d8cd98f00b204e9800998ecf8427eda39a3ee5e6b4b0d3255bfef95601890afd80709.png'
>>> r = req.get('http://api.rest7.com/v1/html_to_image.php?url=http://google.com&format=png')
>>> r.json()['file']
'http://api.rest7.com/temp/1567634400/d41d8cd98f00b204e9800998ecf8427eda39a3ee5e6b4b0d3255bfef95601890afd80709.png'
``` 
Curiouser and curiouser! On visiting above links (plural if they're both the same?), I found that they pointed to an image I had never seen in my life. What is going on!?
And now the image referred to by a link is changing after a few minutes, they now refer to yet another page!
